name: Comment on Pull Requests included in Release
on:
  release:
    types: [published]

jobs:
  comment:
    runs-on: ubuntu-latest
    pull-requests: write
    steps:
      - name: Comment on Pull Requests
        uses: nflaig/release-comment-on-pr@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
