name: Label integration-QA PRs

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repository = context.repo;
            await github.issues.addLabels({
              ...repository,
              issue_number: prNumber,
              labels: ['integration-QA']
            });
