name: Auto Labeler

on:
  pull_request_target:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
