name: release 타겟 PR label생성
on:
  pull_request_target:
    branches:
      - main
    types: [opened, synchronize, reopened]


jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/release-label-config.yml
