name: 통합 QA label생성
on:
  pull_request_target:
    branches:
      - release/*
      - hotfix/*
    types: [opened, reopened]


jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: PR 라벨 추가
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/release-label-config.yml
